name       : switcheroo-control
version    : 2.6
release    : 2
source     :
    - https://gitlab.freedesktop.org/hadess/switcheroo-control/uploads/86ea54ac7ddb901b6bf6e915209151f8/switcheroo-control-2.6.tar.xz : 5d9f952924d969b4c036c806d4175b10d160f9d3598c6b255941e9c943493ca2
license    : GPL-3.0-or-later
component  : system.utils
summary    : D-Bus service to check the availability of dual-GPU
description: |
    D-Bus service to check the availability of dual-GPU
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
